/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/generate-widget-kind-configs.ts
 * 
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

package com.akylas.weather.widgets

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

object WidgetKindConfigs {
    val WIDGET_KINDS = listOf("DailyWeatherWidget", "ForecastWeatherWidget", "HourlyWeatherWidget", "SimpleWeatherWidget", "SimpleWeatherWithClockWidget", "SimpleWeatherWithDateWidget")
    
    private val DEFAULT_SETTINGS = mapOf(
        "SimpleWeatherWithClockWidget" to JsonObject(mapOf(
                "clockBold" to JsonPrimitive(true)
        ))
    )
    
    /**
     * Get default settings for a widget kind
     * Returns null if the widget kind has no settings
     */
    fun getDefaultSettings(widgetKind: String): JsonObject? {
        return DEFAULT_SETTINGS[widgetKind]
    }
    
    /**
     * Create default config for a widget kind
     */
    fun createDefaultKindConfig(widgetKind: String): WidgetConfig {
        return WidgetConfig(
            locationName = "current",
            latitude = 0.0,
            longitude = 0.0,
            model = null,
            provider = null,
            widgetKind = widgetKind,
            iconSet = null,
            settings = getDefaultSettings(widgetKind)
        )
    }
}
