/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by generators/generate-widget-kind-configs.ts
 *
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

import { WidgetConfig } from './WidgetTypes';

export const WIDGET_KIND_CONFIGS: Record<string, WidgetConfig> = {
    DailyWeatherWidget: {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        widgetKind: 'DailyWeatherWidget'
    },
    ForecastWeatherWidget: {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        widgetKind: 'ForecastWeatherWidget'
    },
    HourlyWeatherWidget: {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        widgetKind: 'HourlyWeatherWidget'
    },
    SimpleWeatherWidget: {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        widgetKind: 'SimpleWeatherWidget'
    },
    SimpleWeatherWithClockWidget: {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        widgetKind: 'SimpleWeatherWithClockWidget'
    },
    SimpleWeatherWithDateWidget: {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        widgetKind: 'SimpleWeatherWithDateWidget'
    }
};

export function getDefaultKindConfig(widgetKind: string): WidgetConfig | null {
    return WIDGET_KIND_CONFIGS[widgetKind] || null;
}

export const WIDGET_KINDS = Object.keys(WIDGET_KIND_CONFIGS);
