/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by widget-layouts/generators/generate-widget-kind-configs.ts
 * 
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

import { WidgetConfig } from './WidgetTypes';

export const WIDGET_KIND_CONFIGS: Record<string, WidgetConfig> = {
    'DailyWeatherWidget': {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        model: null,
        provider: null,
        widgetKind: 'DailyWeatherWidget',
        iconSet: null,
        settings: null
    },
    'ForecastWeatherWidget': {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        model: null,
        provider: null,
        widgetKind: 'ForecastWeatherWidget',
        iconSet: null,
        settings: null
    },
    'HourlyWeatherWidget': {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        model: null,
        provider: null,
        widgetKind: 'HourlyWeatherWidget',
        iconSet: null,
        settings: null
    },
    'SimpleWeatherWidget': {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        model: null,
        provider: null,
        widgetKind: 'SimpleWeatherWidget',
        iconSet: null,
        settings: null
    },
    'SimpleWeatherWithClockWidget': {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        model: null,
        provider: null,
        widgetKind: 'SimpleWeatherWithClockWidget',
        iconSet: null,
        settings: {
            "clockBold": true
        }
    },
    'SimpleWeatherWithDateWidget': {
        locationName: 'current',
        latitude: 0,
        longitude: 0,
        model: null,
        provider: null,
        widgetKind: 'SimpleWeatherWithDateWidget',
        iconSet: null,
        settings: null
    }
};

export function getDefaultKindConfig(widgetKind: string): WidgetConfig | null {
    return WIDGET_KIND_CONFIGS[widgetKind] || null;
}

export const WIDGET_KINDS = Object.keys(WIDGET_KIND_CONFIGS);
