#!/usr/bin/env tsx
/**
 * Generate Widget Kind Default Configurations
 * 
 * This script reads widget JSON schemas from widget-layouts/widgets/ and generates:
 * 1. TypeScript file with kind configs for the app
 * 2. Kotlin file with kind configs for Android
 * 3. Swift file with kind configs for iOS
 * 
 * This avoids runtime JSON parsing and code duplication across platforms.
 */

import { readFileSync, writeFileSync } from 'fs';
import { join } from 'path';
import { readdirSync } from 'fs';

interface SettingDefinition {
    type: string;
    default: any;
    title: string;
    description: string;
    values?: any[];
}

interface WidgetKindConfig {
    locationName: string;
    latitude?: number;
    longitude?: number;
    model?: string | null;
    provider?: string | null;
    widgetKind: string;
    iconSet?: string | null;
    settings: Record<string, any> | null;
}

interface WidgetSchema {
    name: string;
    settings?: Record<string, SettingDefinition>;
}

function loadWidgetSchemas(): Map<string, WidgetSchema> {
    const widgetsDir = join(__dirname, '../widgets');
    const schemas = new Map<string, WidgetSchema>();
    
    const files = readdirSync(widgetsDir).filter(f => f.endsWith('.json') && !f.startsWith('.'));
    
    for (const file of files) {
        const content = readFileSync(join(widgetsDir, file), 'utf-8');
        const schema = JSON.parse(content) as WidgetSchema;
        schemas.set(schema.name, schema);
    }
    
    console.log(`Loaded ${schemas.size} widget schemas`);
    return schemas;
}

function extractDefaultSettings(schema: WidgetSchema): Record<string, any> | null {
    if (!schema.settings) {
        return null;
    }
    
    const defaults: Record<string, any> = {};
    for (const [key, setting] of Object.entries(schema.settings)) {
        if ('default' in setting) {
            defaults[key] = setting.default;
        }
    }
    
    return Object.keys(defaults).length > 0 ? defaults : null;
}

function createKindConfig(widgetKind: string, schema: WidgetSchema): WidgetKindConfig {
    return {
        locationName: 'current',
        latitude: 0.0,
        longitude: 0.0,
        model: null,
        provider: null,
        widgetKind,
        iconSet: null,
        settings: extractDefaultSettings(schema)
    };
}

function generateTypeScriptFile(configs: Map<string, WidgetKindConfig>): string {
    const entries = Array.from(configs.entries())
        .map(([kind, config]) => {
            const settingsStr = config.settings 
                ? JSON.stringify(config.settings, null, 4).replace(/\n/g, '\n        ')
                : 'null';
            
            return `    '${kind}': {
        locationName: '${config.locationName}',
        latitude: ${config.latitude},
        longitude: ${config.longitude},
        model: ${config.model === null ? 'null' : `'${config.model}'`},
        provider: ${config.provider === null ? 'null' : `'${config.provider}'`},
        widgetKind: '${config.widgetKind}',
        iconSet: ${config.iconSet === null ? 'null' : `'${config.iconSet}'`},
        settings: ${settingsStr}
    }`;
        })
        .join(',\n');
    
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by widget-layouts/generators/generate-widget-kind-configs.ts
 * 
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

export interface WidgetKindConfig {
    locationName: string;
    latitude?: number;
    longitude?: number;
    model?: string | null;
    provider?: string | null;
    widgetKind: string;
    iconSet?: string | null;
    settings: Record<string, any> | null;
}

export const WIDGET_KIND_CONFIGS: Record<string, WidgetKindConfig> = {
${entries}
};

export function getDefaultKindConfig(widgetKind: string): WidgetKindConfig | null {
    return WIDGET_KIND_CONFIGS[widgetKind] || null;
}

export const WIDGET_KINDS = Object.keys(WIDGET_KIND_CONFIGS);
`;
}

function generateKotlinFile(configs: Map<string, WidgetKindConfig>): string {
    const settingsMappers = Array.from(configs.entries())
        .filter(([, config]) => config.settings !== null)
        .map(([kind, config]) => {
            const settingsEntries = Object.entries(config.settings!)
                .map(([key, value]) => {
                    const valueStr = typeof value === 'string' 
                        ? `JsonPrimitive("${value}")`
                        : typeof value === 'boolean'
                        ? `JsonPrimitive(${value})`
                        : typeof value === 'number'
                        ? `JsonPrimitive(${value})`
                        : `JsonPrimitive("${value}")`;
                    return `                "${key}" to ${valueStr}`;
                })
                .join(',\n');
            
            return `        "${kind}" -> JsonObject(mapOf(
${settingsEntries}
        ))`;
        });
    
    const settingsMap = settingsMappers.length > 0
        ? `    private val DEFAULT_SETTINGS = mapOf(
${settingsMappers.join(',\n')}
    )`
        : `    private val DEFAULT_SETTINGS = emptyMap<String, JsonObject>()`;
    
    const kindsList = Array.from(configs.keys())
        .map(k => `"${k}"`)
        .join(', ');
    
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by widget-layouts/generators/generate-widget-kind-configs.ts
 * 
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

package com.akylas.weather.widgets

import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.JsonPrimitive

object WidgetKindConfigs {
    val WIDGET_KINDS = listOf(${kindsList})
    
${settingsMap}
    
    /**
     * Get default settings for a widget kind
     * Returns null if the widget kind has no settings
     */
    fun getDefaultSettings(widgetKind: String): JsonObject? {
        return DEFAULT_SETTINGS[widgetKind]
    }
    
    /**
     * Create default config for a widget kind
     */
    fun createDefaultKindConfig(widgetKind: String): WidgetConfig {
        return WidgetConfig(
            locationName = "current",
            latitude = 0.0,
            longitude = 0.0,
            model = null,
            provider = null,
            widgetKind = widgetKind,
            iconSet = null,
            settings = getDefaultSettings(widgetKind)
        )
    }
}
`;
}

function generateSwiftFile(configs: Map<string, WidgetKindConfig>): string {
    const settingsCases = Array.from(configs.entries())
        .map(([kind, config]) => {
            if (!config.settings) {
                return `        case "${kind}":
            return nil`;
            }
            
            const settingsEntries = Object.entries(config.settings)
                .map(([key, value]) => {
                    if (typeof value === 'string') {
                        return `                "${key}": "${value}"`;
                    } else if (typeof value === 'boolean') {
                        return `                "${key}": ${value}`;
                    } else if (typeof value === 'number') {
                        return `                "${key}": ${value}`;
                    } else {
                        return `                "${key}": "${value}"`;
                    }
                })
                .join(',\n');
            
            return `        case "${kind}":
            return [
${settingsEntries}
            ]`;
        });
    
    const kindsList = Array.from(configs.keys())
        .map(k => `"${k}"`)
        .join(', ');
    
    return `/**
 * AUTO-GENERATED FILE - DO NOT EDIT
 * Generated by widget-layouts/generators/generate-widget-kind-configs.ts
 * 
 * Widget Kind Default Configurations
 * Contains default configurations for each widget kind, including settings defaults
 * extracted from widget JSON schemas.
 */

import Foundation

/// Widget kind default configurations
class WidgetKindConfigs {
    /// All supported widget kinds
    static let widgetKinds = [${kindsList}]
    
    /// Get default settings for a widget kind
    /// - Parameter widgetKind: The widget kind
    /// - Returns: Dictionary of default settings, or nil if no settings
    static func getDefaultSettings(widgetKind: String) -> [String: Any]? {
        switch widgetKind {
${settingsCases.join('\n')}
        default:
            return nil
        }
    }
    
    /// Create default config for a widget kind
    /// - Parameter widgetKind: The widget kind
    /// - Returns: Widget configuration with defaults from schema
    static func createDefaultKindConfig(widgetKind: String) -> WidgetConfig {
        return WidgetConfig(
            locationName: "current",
            latitude: 0.0,
            longitude: 0.0,
            model: nil,
            provider: nil,
            widgetKind: widgetKind,
            iconSet: nil,
            settings: getDefaultSettings(widgetKind)
        )
    }
}
`;
}

function main() {
    console.log('Generating widget kind configurations...');
    
    // Load widget schemas
    const schemas = loadWidgetSchemas();
    
    // Create kind configs
    const configs = new Map<string, WidgetKindConfig>();
    for (const [kind, schema] of schemas) {
        configs.set(kind, createKindConfig(kind, schema));
    }
    
    console.log(`Generated ${configs.size} kind configurations`);
    
    // Generate TypeScript file
    const tsContent = generateTypeScriptFile(configs);
    const tsPath = join(__dirname, '../../app/services/widgets/WidgetKindConfigs.ts');
    writeFileSync(tsPath, tsContent, 'utf-8');
    console.log(`✓ Generated TypeScript: ${tsPath}`);
    
    // Generate Kotlin file
    const kotlinContent = generateKotlinFile(configs);
    const kotlinPath = join(__dirname, '../../App_Resources/Android/src/main/java/com/akylas/weather/widgets/WidgetKindConfigs.generated.kt');
    writeFileSync(kotlinPath, kotlinContent, 'utf-8');
    console.log(`✓ Generated Kotlin: ${kotlinPath}`);
    
    // Generate Swift file
    const swiftContent = generateSwiftFile(configs);
    const swiftPath = join(__dirname, '../../App_Resources/iOS/extensions/widgets/WidgetKindConfigs.generated.swift');
    writeFileSync(swiftPath, swiftContent, 'utf-8');
    console.log(`✓ Generated Swift: ${swiftPath}`);
    
    console.log('\n✨ Widget kind configurations generated successfully!');
}

// Run if executed directly
if (require.main === module) {
    main();
}

export { main as generateWidgetKindConfigs };
